export enum HairOption {
    None = "none",
    Bald = "bald",
    BuzzCut = "buzzCut",
    Quiff = "quiff",
    BobCut = "bobCut",
    ShortStraight = "shortStraight",
    LongStraight = "longStraight",
    ShortWavy = "shortWavy",
    LongWavy = "longWavy",
    ShortCurly = "shortCurly",
    LongCurly = "longCurly",
    Afro = "afro",
    Ponytail = "ponytail",
    Braids = "braids",
    Dreadlocks = "dreadlocks",
    Mohawk = "mohawk",
}